# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikationen', '0002_auto_20170503_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veroeffentlichungen',
            name='professur',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='veroeffentlichungen',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='veroeffentlichungen',
            unique_together=set([('professur', 'jahr')]),
        ),
    ]
