# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikationen', '0003_auto_20170613_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='veroeffentlichungen',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veroeffentlichungen',
            name='professur',
            field=models.CharField(max_length=200),
        ),
    ]
